# Generated by Django 4.2.9 on 2024-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SendMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("test", "Тест (не использовать)"),
                            ("verify", "Верификация"),
                        ],
                        max_length=256,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "to_email",
                    models.CharField(max_length=256, verbose_name="Имэйл получателя"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активно")),
                ("text", models.TextField()),
            ],
        ),
    ]
