# Generated by Django 4.2.9 on 2024-01-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentorder",
            options={"verbose_name": "Пополнение", "verbose_name_plural": "Пополнения"},
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="email",
            field=models.EmailField(default="test@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="include_service_lava",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="lava_expired",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="lava_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="lava_link",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="project_lava",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="project_lava_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("create", "Создан"),
                    ("expired", "Отменен"),
                    ("success", "Оплачен"),
                ],
                default="create",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="status_lava_num",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_payments_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
