# Generated by Django 4.2.9 on 2024-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paymentorder_options_paymentorder_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="genshin_uid",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
