# Generated by Django 4.2.9 on 2024-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_promocode_calc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calc",
            options={"verbose_name": "Начисление", "verbose_name_plural": "Начисления"},
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={"verbose_name": "Промокод", "verbose_name_plural": "Промокоды"},
        ),
        migrations.RemoveField(
            model_name="calc",
            name="summ",
        ),
        migrations.AddField(
            model_name="calc",
            name="credit",
            field=models.FloatField(default=0, verbose_name="Расход"),
        ),
        migrations.AddField(
            model_name="calc",
            name="debit",
            field=models.FloatField(default=0, verbose_name="Приход"),
        ),
    ]
