# Generated by Django 4.2.9 on 2024-01-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_calc_balance"),
        ("payments", "0006_remove_paymentorder_genshin_uid_and_more"),
    ]

    operations = []
