# Generated by Django 4.2.9 on 2024-01-31 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_merge_20240131_0732"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="promocode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promocode",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="promocode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
