# Generated by Django 4.2.9 on 2024-01-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_promocode_active_promocode_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calc",
            name="promo_code",
        ),
        migrations.AddField(
            model_name="calc",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
