# Generated by Django 4.2.9 on 2024-01-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_activatedpromo"),
        ("payments", "0009_remove_calc_promo_code_calc_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="calc",
            name="promo_using",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calc_promo",
                to="users.activatedpromo",
                verbose_name="Промокод",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="bonus_limit",
            field=models.IntegerField(
                default=1, verbose_name="Количество активаций бонуса на пользователя"
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="limit_for_user",
            field=models.IntegerField(
                default=1, verbose_name="Количество активации на 1 пользователя"
            ),
        ),
    ]
