# Generated by Django 4.2.9 on 2024-02-01 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_calc_promo_using_promocode_bonus_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="percent",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
                verbose_name="Процент",
            ),
        ),
    ]
