# Generated by Django 4.2.9 on 2024-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_promocode_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="manually_approved",
            field=models.BooleanField(default=False),
        ),
    ]
