# Generated by Django 4.2.9 on 2024-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_paymentorder_manually_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("create", "Создан"),
                    ("expired", "Отменен"),
                    ("success", "Оплачен"),
                    ("manually approved", "Одобрен вручную"),
                ],
                default="create",
                max_length=128,
            ),
        ),
    ]
