# Generated by Django 4.2.9 on 2024-02-06 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_calc_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
