# Generated by Django 4.2.9 on 2024-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_useritems_created_at_useritems_updated_at"),
        ("payments", "0017_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="output_items",
                to="users.useritems",
                verbose_name="Предметы",
            ),
        ),
    ]
