# Generated by Django 4.2.9 on 2024-02-10 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0019_remove_output_items_paymentorder_approval_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="approval_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_approval_output",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Одобривший пользователь",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"profile__partner_percent": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
