# Generated by Django 4.2.9 on 2024-02-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_output_approval_user_promocode_from_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositeItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="output",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершенный"),
                    ("proccess", "В процессе"),
                    ("incorrect-details", "Некорректные данные"),
                    ("restock", "Недостаточно денег на балансе"),
                    ("refunded", "Возврат"),
                ],
                default="proccess",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="type",
            field=models.CharField(
                choices=[
                    ("moogold", "Вывод с платформы Moogold"),
                    ("test", "Тестовый вывод (не использовать!)"),
                ],
                default="moogold",
                max_length=64,
            ),
        ),
    ]
