# Generated by Django 4.2.9 on 2024-02-10 22:29

from django.db import migrations, models
import utils.functions.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_alter_promocode_from_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code_data",
            field=models.CharField(
                db_index=True,
                default=utils.functions.id_generator,
                max_length=128,
                unique=True,
            ),
        ),
    ]
