# Generated by Django 4.2.9 on 2024-02-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_compositeitems_output_status_alter_output_type"),
        ("payments", "0022_alter_promocode_code_data"),
    ]

    operations = []
