# Generated by Django 4.2.9 on 2024-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_alter_compositeitems_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositeitems",
            name="crystals_quantity",
            field=models.IntegerField(null=True),
        ),
    ]
