# Generated by Django 4.2.9 on 2024-02-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0025_compositeitems_crystals_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositeitems",
            name="crystals_quantity",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Количество кристаллов"
            ),
        ),
    ]
