# Generated by Django 4.2.9 on 2024-02-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_alter_compositeitems_crystals_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="from_user",
        ),
    ]
