# Generated by Django 4.2.9 on 2024-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_alter_compositeitems_crystals_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositeitems",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="output",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
    ]
