# Generated by Django 4.2.9 on 2024-02-12 11:44

from django.db import migrations, models
import django.db.models.deletion
import utils.functions.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_userprofile_partner"),
        ("payments", "0027_remove_promocode_from_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_data",
                    models.CharField(
                        db_index=True,
                        default=utils.functions.id_generator,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed", models.BooleanField(default=False, verbose_name="Удалено")),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ref_links",
                        to="users.userprofile",
                        verbose_name="От пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферальная ссылка",
                "verbose_name_plural": "Реферальные ссылки",
            },
        ),
    ]
