# Generated by Django 4.2.9 on 2024-02-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_userprofile_partner_percent"),
        ("payments", "0028_reflinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="calc",
            name="ref_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calc_link",
                to="users.activatedlinks",
                verbose_name="Реферальная ссылка",
            ),
        ),
    ]
