# Generated by Django 4.2.9 on 2024-02-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_alter_output_status_purchasecompositeitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasecompositeitems",
            name="output",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_ci_outputs",
                to="payments.output",
                verbose_name="Вывод",
            ),
        ),
    ]
