# Generated by Django 4.2.9 on 2024-02-11 19:43

from django.db import migrations, models
from utils.functions import id_generator_X64


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0029_alter_purchasecompositeitems_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasecompositeitems",
            name="pci_id",
            field=models.CharField(
                default=id_generator_X64,
                max_length=70,
                verbose_name="Внутренний идентификатор",
            ),
        ),
    ]
