# Generated by Django 4.2.9 on 2024-02-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0029_calc_ref_link"),
        ("payments", "0030_alter_purchasecompositeitems_pci_id"),
    ]

    operations = []
