# Generated by Django 4.2.9 on 2024-02-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0031_merge_20240212_1330"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reflinks",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Реферальная ссылка",
                "verbose_name_plural": "Реферальные ссылки",
            },
        ),
    ]
