# Generated by Django 4.2.9 on 2024-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0032_alter_reflinks_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasecompositeitems",
            name="player_id",
            field=models.CharField(
                max_length=512, null=True, verbose_name="Идентификатор аккаунта вывода"
            ),
        ),
    ]
