# Generated by Django 4.2.9 on 2024-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0033_purchasecompositeitems_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="player_id",
            field=models.CharField(
                max_length=512, null=True, verbose_name="Идентификатор аккаунта вывода"
            ),
        ),
    ]
