# Generated by Django 4.2.9 on 2024-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0034_output_player_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasecompositeitems",
            name="server",
            field=models.CharField(max_length=120, null=True, verbose_name="Сервер"),
        ),
    ]
