# Generated by Django 4.2.9 on 2024-02-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_useritems_purchase_composite_item"),
        ("payments", "0035_purchasecompositeitems_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasecompositeitems",
            name="user_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_composite_in_users_item",
                to="users.useritems",
                verbose_name="Выводимый предмет",
            ),
        ),
    ]
