# Generated by Django 4.2.9 on 2024-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0038_output_remove_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="withdrawal_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Стоимость вывода"
            ),
        ),
    ]
