# Generated by Django 4.2.9 on 2024-02-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0038_output_remove_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="calc",
            name="output",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calcs",
                to="payments.output",
                verbose_name="Вывод",
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="type_payments",
            field=models.CharField(
                choices=[
                    ("lava", "Платежная система ЛАВА(LAVA)"),
                    ("yookassa", "Платежная система ЮКасса(Yookassa)"),
                    ("freekassa", "Платежная система ФРИКАССА(Freekassa)"),
                ],
                max_length=64,
            ),
        ),
    ]
