# Generated by Django 4.2.9 on 2024-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0039_output_withdrawal_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="withdrawal_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Стоимость вывода",
            ),
        ),
    ]
