# Generated by Django 4.2.9 on 2024-02-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0040_alter_output_withdrawal_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calc",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="calc",
            name="debit",
        ),
    ]
