# Generated by Django 4.2.9 on 2024-02-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0039_calc_output_alter_paymentorder_type_payments"),
        ("payments", "0040_alter_output_withdrawal_price"),
    ]

    operations = []
