# Generated by Django 4.2.9 on 2024-02-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0041_merge_20240221_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasecompositeitems",
            name="composite_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_composite_in_composite_items",
                to="payments.compositeitems",
                verbose_name="Составная предмета",
            ),
        ),
    ]
