# Generated by Django 4.2.9 on 2024-02-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0041_remove_calc_credit_remove_calc_debit"),
        ("payments", "0042_purchasecompositeitems_composite_item"),
    ]

    operations = []
