# Generated by Django 4.2.9 on 2024-02-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0043_merge_20240223_1600"),
        ("payments", "0043_merge_20240223_2014"),
    ]

    operations = []
