# Generated by Django 4.2.9 on 2024-02-24 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from utils.functions import ref_output_id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0044_merge_20240223_1607"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_output_id",
                    models.CharField(
                        default=ref_output_id_generator,
                        max_length=72,
                        verbose_name="Идектификатор",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Вывод на банковскую карту"),
                            ("cryptocurrency", "Вывод на криптокошелек"),
                            ("sbp", "Вывод по СБП"),
                        ],
                        default="card",
                        max_length=32,
                        verbose_name="Тип платежа",
                    ),
                ),
                ("sum", models.FloatField(verbose_name="Сумма вывода")),
                (
                    "comment",
                    models.TextField(
                        max_length=1024, null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=32, null=True, verbose_name="Номер карты"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13, null=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "crypto_number",
                    models.CharField(
                        max_length=2048, null=True, verbose_name="Номер криптокошелька"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Созданный"),
                            ("completed", "Завершенный"),
                            ("canceled", "Отмененный"),
                        ],
                        default="created",
                        verbose_name="Статус вывода",
                    ),
                ),
                ("active", models.CharField(default=True, verbose_name="Активный")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_ref_outputs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вывод с реферальной программы",
                "verbose_name_plural": "Выводы с реферальных программ",
            },
        ),
    ]
