# Generated by Django 4.2.9 on 2024-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0045_refoutput"),
    ]

    operations = [
        migrations.AddField(
            model_name="refoutput",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="Удаленный"),
        ),
    ]
