# Generated by Django 4.2.9 on 2024-02-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0046_refoutput_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refoutput",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
