# Generated by Django 4.2.9 on 2024-02-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0049_rename_lava_link_paymentorder_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentorder",
            old_name="include_service_lava",
            new_name="include_service",
        ),
    ]
