# Generated by Django 4.2.9 on 2024-04-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0051_promocode_remaining_activations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calc",
            options={
                "ordering": ("id",),
                "verbose_name": "Начисление",
                "verbose_name_plural": "Начисления",
            },
        ),
        migrations.AlterModelOptions(
            name="compositeitems",
            options={
                "ordering": ("id",),
                "verbose_name": "Составной предмет",
                "verbose_name_plural": "Составные предметов",
            },
        ),
        migrations.AlterModelOptions(
            name="output",
            options={
                "ordering": ("id",),
                "verbose_name": "Вывод предмета",
                "verbose_name_plural": "Выводы предметов",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentorder",
            options={
                "ordering": ("id",),
                "verbose_name": "Пополнение",
                "verbose_name_plural": "Пополнения",
            },
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ("id",),
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasecompositeitems",
            options={
                "ordering": ("id",),
                "verbose_name": "Закупка на сторонем сервисе",
                "verbose_name_plural": "Закупки на стороних сервисах",
            },
        ),
        migrations.AlterModelOptions(
            name="refoutput",
            options={
                "ordering": ("id",),
                "verbose_name": "Вывод с реферальной программы",
                "verbose_name_plural": "Выводы с реферальных программ",
            },
        ),
    ]
