# Generated by Django 4.2.9 on 2024-04-07 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0053_alter_calc_options_alter_compositeitems_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="output",
            name="user_cancel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_cancel_outputs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отменивший пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Завершенный"),
                    ("proccess", "В процессе"),
                    ("technical-error", "Техническая ошибка"),
                    ("canceled", "Отменен"),
                ],
                default="proccess",
                max_length=32,
            ),
        ),
    ]
