# Generated by Django 4.2.9 on 2024-04-08 13:55

from django.db import migrations, models
import utils.functions.output_id_generator
from utils.functions import output_id_generator, ref_output_id_generator


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0054_output_user_cancel_alter_output_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="output",
            name="comment",
            field=models.TextField(
                blank=True, db_index=True, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="output",
            name="output_id",
            field=models.CharField(
                db_index=True,
                default=output_id_generator,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="order_id",
            field=models.CharField(
                db_index=True,
                default=utils.functions.payments_id_generator.payment_order_id_generator,
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="refoutput",
            name="comment",
            field=models.TextField(
                db_index=True, max_length=1024, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="refoutput",
            name="ref_output_id",
            field=models.CharField(
                db_index=True,
                default=ref_output_id_generator,
                max_length=72,
                verbose_name="Идектификатор",
            ),
        ),
    ]
