# Generated by Django 4.2.9 on 2024-01-29 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Фотография пользователя"
                    ),
                ),
                (
                    "locale",
                    models.CharField(default="ru", max_length=8, verbose_name="Локаль"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Верифицирован"),
                ),
                (
                    "individual_percent",
                    models.FloatField(default=1, verbose_name="Индивидуальный процент"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
