# Generated by Django 4.2.9 on 2024-01-30 10:02

from django.db import migrations, models
import utils.functions.generate_upload_name


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                upload_to=utils.functions.generate_upload_name,
                verbose_name="Фотография пользователя",
            ),
        ),
    ]
