# Generated by Django 4.2.9 on 2024-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritems",
            name="from_case",
            field=models.BooleanField(default=False, verbose_name="Выпал из кейса"),
        ),
    ]
