# Generated by Django 4.2.9 on 2024-01-31 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0009_remove_calc_promo_code_calc_comment"),
        ("users", "0005_useritems_from_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivatedPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_using",
                    models.BooleanField(
                        default=False, verbose_name="Бонус к пополнению использован"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.promocode",
                        verbose_name="Промо",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активированный промокод",
                "verbose_name_plural": "Активированные промокоды",
            },
        ),
    ]
