# Generated by Django 4.2.9 on 2024-02-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_promocode_percent"),
        ("users", "0007_useritems_withdrawn"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritems",
            name="calc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saled_items",
                to="payments.calc",
                verbose_name="Начисление",
            ),
        ),
    ]
