# Generated by Django 4.2.9 on 2024-02-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_raritycategory_rarity_color"),
        ("users", "0008_useritems_calc"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritems",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_items",
                to="cases.case",
                to_field="case_id",
                verbose_name="Кейс",
            ),
        ),
    ]
