# Generated by Django 4.2.9 on 2024-02-08 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userprofile_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritems",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создан",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useritems",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
    ]
