# Generated by Django 4.2.9 on 2024-02-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_remove_output_items_paymentorder_approval_user"),
        ("users", "0011_useritems_created_at_useritems_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritems",
            name="output",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="output_items",
                to="payments.output",
                verbose_name="Вывод",
            ),
        ),
    ]
