# Generated by Django 4.2.9 on 2024-02-10 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_useritems_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="partner",
            field=models.BooleanField(default=False, verbose_name="Партнёр"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="partner_percent",
            field=models.FloatField(
                default=0.03,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Процент с пополнений",
            ),
        ),
    ]
