# Generated by Django 4.2.9 on 2024-02-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_userprofile_partner_userprofile_partner_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="partner",
        ),
    ]
