# Generated by Django 4.2.9 on 2024-02-12 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_activatedlinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="partner_percent",
            field=models.FloatField(
                default=1.03,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
                verbose_name="Процент с пополнений",
            ),
        ),
    ]
