# Generated by Django 4.2.9 on 2024-02-13 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0031_merge_20240212_1330"),
        ("users", "0017_useritems_withdrawal_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedlinks",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_links",
                to="payments.reflinks",
                verbose_name="Промо",
            ),
        ),
        migrations.AlterField(
            model_name="activatedlinks",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
