# Generated by Django 4.2.9 on 2024-02-13 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_activatedlinks_link_alter_activatedlinks_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="partner_income",
            field=models.FloatField(
                default=0.03,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Доход с пополнения по реферальной ссылке",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="partner_percent",
            field=models.FloatField(
                default=1.03,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
                verbose_name="Бонус с реферальной ссылки",
            ),
        ),
    ]
