# Generated by Django 4.2.9 on 2024-02-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0035_purchasecompositeitems_server"),
        ("users", "0019_userprofile_partner_income_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritems",
            name="purchase_composite_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_composite_in_users_items",
                to="payments.purchasecompositeitems",
                verbose_name="Закупка составных предметов",
            ),
        ),
    ]
