# Generated by Django 4.2.9 on 2024-02-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_useritems_purchase_composite_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useritems",
            name="purchase_composite_item",
        ),
    ]
