# Generated by Django 4.2.9 on 2024-02-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_useritems_purchase_composite_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="withdrawal_is_allowed",
            field=models.BooleanField(default=True, verbose_name="Разрешение на вывод"),
        ),
    ]
