# Generated by Django 4.2.9 on 2024-02-18 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0025_contests"),
        ("users", "0021_remove_useritems_purchase_composite_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestsWinners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.contests",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.item",
                        verbose_name="Приз",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Победитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Победитель конкурса",
                "verbose_name_plural": "Победители конкурсов",
            },
        ),
    ]
