# Generated by Django 4.2.9 on 2024-02-19 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0026_conditioncase_description_contests_next_start_and_more"),
        ("users", "0022_contestswinners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestswinners",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="winners",
                to="cases.contests",
                verbose_name="Конкурс",
            ),
        ),
        migrations.AlterField(
            model_name="contestswinners",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contestswinners",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contests_win",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Победитель",
            ),
        ),
    ]
