# Generated by Django 4.2.9 on 2024-02-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_userprofile_withdrawal_is_allowed"),
        ("users", "0024_useritems_contest"),
    ]

    operations = []
