# Generated by Django 4.2.9 on 2024-02-23 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_merge_20240221_1501"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="individual_percent",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name="Индивидуальный процент",
            ),
        ),
    ]
