# Generated by Django 4.2.9 on 2024-02-26 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0028_item_upgrade"),
        ("users", "0026_alter_userprofile_individual_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpgradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="Успешный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Обновлён"),
                ),
                (
                    "desired",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Предмет",
                        to="cases.item",
                        verbose_name="Желаемый предмет",
                    ),
                ),
                (
                    "upgraded",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upgraded_item",
                        to="users.useritems",
                        verbose_name="Возвышаемый предмет",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upgrade_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
