# Generated by Django 4.2.9 on 2024-02-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0028_item_upgrade"),
        ("users", "0027_userupgradehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupgradehistory",
            name="balance",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="Баланс"
            ),
        ),
        migrations.RemoveField(
            model_name="userupgradehistory",
            name="desired",
        ),
        migrations.RemoveField(
            model_name="userupgradehistory",
            name="upgraded",
        ),
        migrations.AddField(
            model_name="userupgradehistory",
            name="desired",
            field=models.ManyToManyField(
                blank=True,
                related_name="Предмет",
                to="cases.item",
                verbose_name="Желаемый предмет",
            ),
        ),
        migrations.AddField(
            model_name="userupgradehistory",
            name="upgraded",
            field=models.ManyToManyField(
                blank=True,
                related_name="upgraded_item",
                to="users.useritems",
                verbose_name="Возвышаемый предмет",
            ),
        ),
    ]
