# Generated by Django 4.2.9 on 2024-03-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0028_userupgradehistory_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(max_length=256, verbose_name="Токен"),
                ),
                ("email", models.CharField(max_length=256, verbose_name="Имэйл")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "to_date",
                    models.DateTimeField(blank=True, verbose_name="Действует до"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_verifys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Верификация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Верификация пользователя",
                "verbose_name_plural": "Верификации пользователей",
            },
        ),
    ]
