# Generated by Django 4.2.9 on 2024-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_userprofile_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
