# Generated by Django 4.2.9 on 2024-03-07 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_alter_userprofile_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="individual_percent",
            field=models.FloatField(
                default=1,
                validators=[django.core.validators.MinValueValidator(-1)],
                verbose_name="Индивидуальный процент",
            ),
        ),
    ]
