# Generated by Django 4.2.9 on 2024-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_userprofile_individual_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_username",
            field=models.CharField(
                max_length=512, null=True, verbose_name="Телеграм никнейм"
            ),
        ),
    ]
