# Generated by Django 4.2.9 on 2024-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_alter_activatedlinks_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="balance_save",
            field=models.FloatField(default=0, verbose_name="Сохранённый баланс"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="debit_save",
            field=models.FloatField(default=0, verbose_name="Сохранённый депозит"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="output_save",
            field=models.FloatField(default=0, verbose_name="Сохранённый вывод"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="winrate_save",
            field=models.FloatField(
                default=0, verbose_name="Сохранённый процент побед"
            ),
        ),
    ]
