# Generated by Django 4.2.9 on 2024-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_userprofile_balance_save_userprofile_debit_save_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="player_id",
            field=models.CharField(
                max_length=12, null=True, verbose_name="Genshin UID"
            ),
        ),
    ]
