# Generated by Django 4.2.9 on 2024-04-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_alter_userprofile_telegram_username"),
        ("users", "0037_userprofile_player_id"),
    ]

    operations = []
