# Generated by Django 4.2.9 on 2024-04-16 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0038_merge_20240411_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestswinners",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contests_win",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Победитель",
            ),
        ),
    ]
