version: '3.9'

services:
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    env_file:
      - .env
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    env_file:
      - .env
  celery_worker:
    build: .
    restart: always
    command: /bin/sh ./scripts/celery_worker.sh
    environment:
      POSTGRES_HOST: postgres-dev
      REDIS_HOST: redis
    env_file:
      - .env
  celery_beat:
    build: .
    restart: always
    command: /bin/sh ./scripts/celery_beat.sh
    environment:
      POSTGRES_HOST: postgres-dev
      REDIS_HOST: redis
    env_file:
      - .env
  legadrop:
    build: .
    restart: always
    command: /bin/sh ./start.sh
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - .env
    ports:
      - "8000:8000" 