# Generated by Django 4.2.9 on 2024-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_genericsettings_online_buff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="domain_url",
            field=models.CharField(
                default="legadrop.org",
                help_text="Вводим только домен, без протокола. По дефолту связывается по https",
                max_length=256,
                verbose_name="Домен реферальной ссылки",
            ),
        ),
        migrations.AddField(
            model_name="genericsettings",
            name="redirect_domain",
            field=models.CharField(
                default="legadrop.org",
                help_text="Вводим только домен, без протокола. По дефолту связывается по https",
                max_length=256,
                verbose_name="Домен для переадресации",
            ),
        ),
    ]
