# Generated by Django 4.2.9 on 2024-02-23 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_genericsettings_domain_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="default_mark_up_case",
            field=models.FloatField(
                default=0.1,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Дефолтная наценка на кейсы",
            ),
        ),
    ]
