# Generated by Django 4.2.9 on 2024-02-27 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_genericsettings_min_ref_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="base_upgrade_percent",
            field=models.FloatField(
                default=0.85,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Базовая ставка расчёта",
            ),
        ),
        migrations.AddField(
            model_name="genericsettings",
            name="base_upper_ratio",
            field=models.FloatField(
                default=1.25,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Минимальный коэффициент возвышения",
            ),
        ),
        migrations.AddField(
            model_name="genericsettings",
            name="minimal_price_upgrade",
            field=models.FloatField(
                default=20,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Минимальная ставка при апгрейде",
            ),
        ),
    ]
