# Generated by Django 4.2.9 on 2024-02-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_genericsettings_base_upgrade_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="notify_domain",
            field=models.CharField(
                default="legadrop.org",
                help_text="Вводим только домен, без протокола. По дефолту связывается по https",
                max_length=256,
                verbose_name="Домен для уведомлений. По дефолту связывается по https",
            ),
        ),
    ]
