# Generated by Django 4.2.9 on 2024-02-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_genericsettings_notify_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="free_kassa_failure_url",
            field=models.CharField(
                default="https://legadrop.org",
                max_length=256,
                verbose_name="Домен для переадресации после оплаты в случае неудачи",
            ),
        ),
        migrations.AddField(
            model_name="genericsettings",
            name="free_kassa_success_url",
            field=models.CharField(
                default="https://legadrop.org",
                max_length=256,
                verbose_name="Домен для переадресации после оплаты в случае успеха",
            ),
        ),
    ]
