# Generated by Django 4.2.9 on 2024-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_genericsettings_email_verify_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="telegram_verify_bot_token",
            field=models.CharField(
                max_length=512,
                null=True,
                verbose_name="Токен телеграмм бота для подтверждения подписок",
            ),
        ),
    ]
