# Generated by Django 4.2.9 on 2024-01-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        default="At5zh0Zu8", editable=False, max_length=9, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "image",
                    models.ImageField(null=True, upload_to="", verbose_name="Картинка"),
                ),
                ("price", models.FloatField(default=0, verbose_name="Стоимость")),
                (
                    "case_free",
                    models.BooleanField(default=False, verbose_name="Кейс бесплатный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Кейс",
                "verbose_name_plural": "Кейсы",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        default="Vp8lUVSB2", editable=False, max_length=9, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="ConditionCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "condition_id",
                    models.CharField(
                        default="Ho647rRZr", editable=False, max_length=9, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("calc", "Начисление"), ("time", "Время")],
                        max_length=128,
                    ),
                ),
                ("price", models.FloatField(null=True, verbose_name="Сумма внесения")),
                ("time", models.TimeField(verbose_name="Время проверки")),
                (
                    "time_reboot",
                    models.TimeField(verbose_name="Снова открыть кейс через"),
                ),
            ],
            options={
                "verbose_name": "Условие",
                "verbose_name_plural": "Условия",
            },
        ),
        migrations.CreateModel(
            name="RarityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rarity_id",
                    models.CharField(
                        default="Qh84YxQza", editable=False, max_length=9, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("category_percent", models.FloatField(default=1)),
            ],
            options={
                "verbose_name": "Категория редкости",
                "verbose_name_plural": "Категории редкости",
            },
        ),
        migrations.CreateModel(
            name="OpenedCases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_id",
                    models.CharField(
                        default="Za5h9UWod", editable=False, max_length=9, unique=True
                    ),
                ),
                (
                    "open_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата открытия кейса"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.case",
                        to_field="case_id",
                        verbose_name="Кейс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Открытый кейс",
                "verbose_name_plural": "Открытые кейсы",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        default="Uy5gzyf6f", editable=False, max_length=9, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("price", models.FloatField(default=0, verbose_name="Стоимость")),
                (
                    "price_in_rubles",
                    models.FloatField(default=0, verbose_name="Стоимость в рублях"),
                ),
                (
                    "sale",
                    models.BooleanField(
                        default=False, verbose_name="Продаётся в магазине"
                    ),
                ),
                ("color", models.CharField(max_length=128, verbose_name="Цвет")),
                ("image", models.ImageField(upload_to="", verbose_name="Картинка")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "step_down_factor",
                    models.FloatField(default=1, verbose_name="Понижающий фактор"),
                ),
                (
                    "rarity_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="cases.raritycategory",
                        to_field="rarity_id",
                        verbose_name="Категория уникальности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приз",
                "verbose_name_plural": "Призы",
            },
        ),
        migrations.AddField(
            model_name="case",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="cases.category",
                to_field="category_id",
                verbose_name="Категория кейса",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="conditions",
            field=models.ManyToManyField(
                to="cases.conditioncase", verbose_name="Условия открытия кейса"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="items",
            field=models.ManyToManyField(
                to="cases.item", verbose_name="Предметы в кейсе"
            ),
        ),
    ]
