# Generated by Django 4.2.9 on 2024-01-28 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.functions.id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_id",
            field=models.CharField(
                default=utils.functions.id_generator,
                editable=False,
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="conditions",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="cases.conditioncase",
                verbose_name="Условия открытия кейса",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_id",
            field=models.CharField(
                default=utils.functions.id_generator,
                editable=False,
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="conditioncase",
            name="condition_id",
            field=models.CharField(
                default=utils.functions.id_generator,
                editable=False,
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_id",
            field=models.CharField(
                default=utils.functions.id_generator,
                editable=False,
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="openedcases",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_opening",
                to="cases.case",
                to_field="case_id",
                verbose_name="Кейс",
            ),
        ),
        migrations.AlterField(
            model_name="openedcases",
            name="history_id",
            field=models.CharField(
                default=utils.functions.id_generator,
                editable=False,
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="openedcases",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opened_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="raritycategory",
            name="rarity_id",
            field=models.CharField(
                default=utils.functions.id_generator,
                editable=False,
                max_length=9,
                unique=True,
            ),
        ),
    ]
