# Generated by Django 4.2.9 on 2024-01-30 10:02

from django.db import migrations, models
import django.db.models.deletion
import utils.functions.generate_upload_name


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_case_conditions_useritems"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предметы"},
        ),
        migrations.AlterField(
            model_name="case",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=utils.functions.generate_upload_name,
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                upload_to=utils.functions.generate_upload_name,
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="useritems",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_items",
                to="cases.item",
                verbose_name="Предмет",
            ),
        ),
    ]
