# Generated by Django 4.2.9 on 2024-01-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_alter_item_options_alter_case_image_alter_item_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useritems",
            options={
                "verbose_name": "Предмет пользователя",
                "verbose_name_plural": "Предметы пользователей",
            },
        ),
    ]
