# Generated by Django 4.2.9 on 2024-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_useritems_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserItems",
        ),
    ]
