# Generated by Django 4.2.9 on 2024-01-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_delete_useritems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="price_in_rubles",
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_price",
            field=models.FloatField(default=0, verbose_name="Закупочная цена"),
        ),
    ]
