# Generated by Django 4.2.9 on 2024-01-31 00:50

from django.db import migrations, models
import utils.functions.generate_upload_name


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_remove_item_price_in_rubles_item_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="conditions",
            field=models.ManyToManyField(
                blank=True,
                to="cases.conditioncase",
                verbose_name="Условия открытия кейса",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.functions.generate_upload_name,
                verbose_name="Картинка",
            ),
        ),
    ]
