# Generated by Django 4.2.9 on 2024-01-31 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_item_removed_item_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="percent_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Процент от начальной цены при продаже",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sale_price",
            field=models.FloatField(default=0, verbose_name="Цена продажи"),
        ),
    ]
