# Generated by Django 4.2.9 on 2024-02-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_alter_item_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="color",
        ),
    ]
