# Generated by Django 4.2.9 on 2024-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_remove_item_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="removed",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="case",
            name="translit_name",
            field=models.CharField(
                default="name",
                editable=False,
                unique=True,
                verbose_name="Транслитерация названия",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="conditioncase",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
