# Generated by Django 4.2.9 on 2024-02-03 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_case_removed_case_translit_name_case_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conditioncase",
            old_name="type",
            new_name="type_condition",
        ),
    ]
