# Generated by Django 4.2.9 on 2024-02-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_rename_type_conditioncase_type_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="items",
            field=models.ManyToManyField(
                limit_choices_to={"removed": False},
                to="cases.item",
                verbose_name="Предметы в кейсе",
            ),
        ),
    ]
