# Generated by Django 4.2.9 on 2024-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_raritycategory_rarity_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditioncase",
            name="price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Сумма внесения"
            ),
        ),
        migrations.AlterField(
            model_name="conditioncase",
            name="time",
            field=models.TimeField(verbose_name="Глубина проверки"),
        ),
        migrations.AlterField(
            model_name="openedcases",
            name="open_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата открытия кейса"
            ),
        ),
    ]
