# Generated by Django 4.2.9 on 2024-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_alter_conditioncase_price_alter_conditioncase_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditioncase",
            name="time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Глубина проверки"
            ),
        ),
    ]
