# Generated by Django 4.2.9 on 2024-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_alter_conditioncase_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="openedcases",
            name="win",
            field=models.BooleanField(
                default=False, verbose_name="Предмет дороже кейса"
            ),
        ),
    ]
