# Generated by Django 4.2.9 on 2024-02-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_openedcases_win"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_output",
            field=models.BooleanField(
                default=True, verbose_name="Выводимый/Не выводимый"
            ),
        ),
    ]
