# Generated by Django 4.2.9 on 2024-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_item_is_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="crystals_quantity",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Количество кристаллов"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[("crystal", "Кристалл"), ("blessing", "Благословение")],
                max_length=32,
                null=True,
                verbose_name="Тип предмета",
            ),
        ),
    ]
