# Generated by Django 4.2.9 on 2024-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_item_crystals_quantity_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ghost_crystals_quantity",
            field=models.IntegerField(
                default=0,
                null=True,
                verbose_name="Количество кристаллов для призрачного предмета",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("crystal", "Кристалл"),
                    ("blessing", "Благословение"),
                    ("ghost_item", "Призрачный пердмет"),
                ],
                max_length=32,
                null=True,
                verbose_name="Тип предмета",
            ),
        ),
    ]
