# Generated by Django 4.2.9 on 2024-02-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_item_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="ghost_crystals_quantity",
        ),
    ]
