# Generated by Django 4.2.9 on 2024-02-18 01:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.functions.id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0024_remove_item_ghost_crystals_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contest_id",
                    models.CharField(
                        default=utils.functions.id_generator,
                        editable=False,
                        max_length=9,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "timer",
                    models.DurationField(
                        default=datetime.timedelta(days=1),
                        help_text="Формат указания в виде 'дни часы:минуты:секунды'",
                        verbose_name="Промежуток",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "one_time",
                    models.BooleanField(
                        default=False, verbose_name="Конкурс одноразовый"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                ("removed", models.BooleanField(default=False, verbose_name="Удалено")),
                (
                    "conditions",
                    models.ManyToManyField(
                        related_name="contests",
                        to="cases.conditioncase",
                        verbose_name="Условия участия",
                    ),
                ),
                (
                    "current_award",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_award_contests",
                        to="cases.item",
                        verbose_name="Текущий приз",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        limit_choices_to={"removed": False},
                        related_name="contests",
                        to="cases.item",
                        verbose_name="Список призов",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конкурс",
                "verbose_name_plural": "Конкурсы",
            },
        ),
    ]
