# Generated by Django 4.2.9 on 2024-02-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_contests"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioncase",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание для пользователя"
            ),
        ),
        migrations.AddField(
            model_name="contests",
            name="next_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время следующего розыгрыша"
            ),
        ),
        migrations.AlterField(
            model_name="contests",
            name="current_award",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_award_contests",
                to="cases.item",
                to_field="item_id",
                verbose_name="Текущий приз",
            ),
        ),
    ]
