# Generated by Django 4.2.9 on 2024-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0028_item_upgrade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="purchase_price",
        ),
        migrations.AlterField(
            model_name="item",
            name="is_output",
            field=models.BooleanField(
                default=True, verbose_name="Выводимый предмет с сервиса"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="service",
            field=models.CharField(
                choices=[
                    ("moogold", "Предмет с Moogold"),
                    ("test", "Тестовый (не использовать!)"),
                ],
                max_length=32,
                null=True,
                verbose_name="Сервис",
            ),
        ),
    ]
