# Generated by Django 4.2.9 on 2024-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0029_remove_item_purchase_price_alter_item_is_output_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditioncase",
            name="type_condition",
            field=models.CharField(
                choices=[
                    ("calc", "Начисление"),
                    ("time", "Время"),
                    ("group_vk", "Подписка на группу VK"),
                ],
                max_length=128,
            ),
        ),
    ]
