# Generated by Django 4.2.9 on 2024-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0030_alter_conditioncase_type_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioncase",
            name="group_id_vk",
            field=models.CharField(
                max_length=1024,
                null=True,
                verbose_name="ID группы 'vk.com' формат club########",
            ),
        ),
    ]
