# Generated by Django 4.2.9 on 2024-03-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_conditioncase_group_id_tg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openedcases",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_wins",
                to="cases.item",
                verbose_name="Выигранный айтем",
            ),
        ),
    ]
