# Generated by Django 4.2.9 on 2024-04-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0036_alter_case_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(
                db_index=True, max_length=256, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=256, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="conditioncase",
            name="description",
            field=models.TextField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Описание для пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="conditioncase",
            name="name",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="contests",
            name="name",
            field=models.CharField(
                db_index=True, max_length=256, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                db_index=True, max_length=256, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="raritycategory",
            name="name",
            field=models.CharField(
                db_index=True, max_length=256, verbose_name="Название"
            ),
        ),
    ]
