# Generated by Django 4.2.9 on 2024-04-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0037_alter_case_name_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="percent_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="step_down_factor",
        ),
    ]
